name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build
      run: nix develop --command make build
    - name: Test
      run: nix develop --command make test-verbose
    - name: Lint
      run: nix develop --command make lint
    - name: Tidy
      run: nix develop --command go mod tidy
    - name: Check if tidy changed anything
      run: git diff --exit-code
